import ContentLayout from "../components/ContentLayout.jsx";

export const meta = {
  outFile: "toneara.html",
  title: "Toneara — Clark X Group",
  description:
    "Toneara turns a text brief into a playable instrumental, right in your browser -- no account, no API key, no server, and nothing sent anywhere. A Clark X Group venture.",
};

const FACTS = [
  {
    title: "Nothing leaves the browser",
    meta: "A strict content security policy allows no third-party runtime requests. Prompts, settings, and generated audio stay on the device.",
  },
  {
    title: "No account, ever",
    meta: "No signup, API key, backend, or payment of any kind. Open the page and generate.",
  },
  {
    title: "Twelve variations, deterministic",
    meta: "Each brief seeds a deterministic generation engine -- the same brief always produces the same twelve options, not a trained model's guess.",
  },
  {
    title: "Installable and offline",
    meta: "Ships as a progressive web app with offline app-shell caching, so it starts even without a connection.",
  },
  {
    title: "Real export, not a preview",
    meta: "Waveform, seeking, regeneration, and a straight WAV download -- plus a portable, validated project file you can hand off or re-import.",
  },
  {
    title: "Source-visible, not open-source",
    meta: "The engine is visible for evaluation on GitHub, but redistribution, hosted deployment, and commercial use require written permission -- proprietary, not permissively licensed.",
  },
];

const CONTROLS = [
  { title: "Genre", meta: "Electronic, hip-hop, ambient, or cinematic." },
  { title: "Mood", meta: "Focused, uplifting, dark, or dreamy." },
  { title: "Length", meta: "10, 20, or 30 seconds, at your chosen tempo." },
];

export default function TonearaSpotlight() {
  return (
    <ContentLayout>
      <span className="kicker">Clark X Group / Venture</span>
      <span className="badge pending">
        <i /> Release candidate 0.1.0
      </span>
      <h1>
        Describe a sound. Hear it in seconds.{" "}
        <span className="accent-word">Nothing</span> leaves your browser.
      </h1>
      <p className="lead">
        Toneara turns a short brief -- genre, mood, tempo, length -- into a playable instrumental
        sketch, generated entirely on your device. No account to create, no API key to paste in, no
        server in between. It's built for the five seconds before you'd reach for a finished
        production tool, not to replace one.
      </p>

      <h2>Set the brief</h2>
      <div className="grid">
        {CONTROLS.map((c) => (
          <div key={c.title} className="card" style={{ margin: 0 }}>
            <p className="tile-title" style={{ marginBottom: "4px" }}>
              {c.title}
            </p>
            <p className="tile-meta" style={{ marginBottom: 0 }}>
              {c.meta}
            </p>
          </div>
        ))}
      </div>
      <p>
        Twelve variations come back from that brief -- generated by a seeded, deterministic engine,
        not a trained model guessing at your prompt. The same brief always produces the same twelve
        options, which makes results reproducible instead of a slot machine.
      </p>

      <h2>Built to need nothing from you</h2>
      <div className="grid">
        {FACTS.map((f) => (
          <div key={f.title} className="card" style={{ margin: 0 }}>
            <p className="tile-title" style={{ marginBottom: "4px" }}>
              {f.title}
            </p>
            <p className="tile-meta" style={{ marginBottom: 0 }}>
              {f.meta}
            </p>
          </div>
        ))}
      </div>

      <p className="grid-group-label" style={{ marginTop: "var(--sp-8)" }}>
        How it compares
      </p>
      <div className="grid">
        <a className="tile" href="/comparisons/toneara-vs-soundraw">
          <span className="tile-title">Toneara vs. Soundraw</span>
          <span className="tile-meta">
            A trained model behind a subscription vs. a private, offline sketch engine that makes
            no such claim
          </span>
        </a>
      </div>

      <div className="card" style={{ marginTop: "var(--sp-10)" }}>
        <span className="kicker" style={{ marginBottom: "var(--sp-2)" }}>
          Get updates
        </span>
        <p style={{ marginBottom: "var(--sp-2)" }}>
          Leave your email and we&apos;ll let you know as Toneara moves past release-candidate:
        </p>
        <form className="signup-form" id="tonearaBetaForm" noValidate>
          <label htmlFor="tonearaBetaEmail" className="sr-only">
            Email
          </label>
          <input
            type="email"
            id="tonearaBetaEmail"
            name="email"
            placeholder="you@company.com"
            required
            autoComplete="email"
          />
          <button type="submit">Join the list</button>
        </form>
        <p className="signup-msg" id="tonearaBetaMsg" role="status" aria-live="polite" />
        <script
          dangerouslySetInnerHTML={{
            __html: `(function(){
  var API_BASE = ["localhost", "127.0.0.1", ""].indexOf(location.hostname) !== -1
    ? "http://localhost:8000"
    : "https://api.usemeritai.com";
  var form = document.getElementById("tonearaBetaForm");
  var input = document.getElementById("tonearaBetaEmail");
  var msg = document.getElementById("tonearaBetaMsg");
  form.addEventListener("submit", function (e) {
    e.preventDefault();
    var emailValue = input.value.trim();
    if (!emailValue) return;
    var btn = form.querySelector("button");
    var label = btn.textContent;
    btn.disabled = true;
    btn.textContent = "Joining…";
    var controller = new AbortController();
    var timeoutId = setTimeout(function () { controller.abort(); }, 15000);
    fetch(API_BASE + "/waitlist", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ email: emailValue, source: "toneara-beta" }),
      signal: controller.signal,
    })
      .then(function (res) {
        clearTimeout(timeoutId);
        if (!res.ok) throw new Error("bad status");
        msg.textContent = "You're on the list.";
        msg.className = "signup-msg ok";
        form.reset();
      })
      .catch(function (err) {
        clearTimeout(timeoutId);
        msg.textContent = err && err.name === "AbortError"
          ? "This is taking longer than expected — try again in a moment."
          : "Couldn't reach the server — try again in a moment.";
        msg.className = "signup-msg err";
      })
      .finally(function () {
        btn.disabled = false;
        btn.textContent = label;
      });
  });
})();`,
          }}
        />
      </div>

      <p style={{ marginTop: "var(--sp-6)" }}>
        Toneara is an independent Clark X Group venture -- source is visible for evaluation on
        GitHub: <a href="https://github.com/drewc611/TONEARA">github.com/drewc611/TONEARA</a>.
        Reuse, redistribution, and commercial deployment require written permission; see the
        repository&apos;s license.
      </p>
    </ContentLayout>
  );
}
